version: "3.8"

services:
  spring-cleanarch:
    container_name: spring-cleanarch
    image: spring-cleanarch:latest
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 700M
      restart_policy:
        condition: on-failure